version: 2

run:
  go: "1.24"
  build-tags:
    - cgo
  exclude-dirs:
    - vendor
    - fyne-cross
  exclude-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - govet
    - ineffassign
    #- staticcheck
    - unused
    #- gocritic
    #- gosec # Security linter
    - errcheck # Error checking
    #- revive # Opinionated linter
    - whitespace # Enforce whitespace rules
    - bodyclose # Ensure files/sockets are closed
  disable:
    - staticcheck

linters-settings:
  perfsprint:
    int-conversion: false
    err-error: false
    errorf: true
    sprintf1: false
    strconcat: false
  revive:
    enable-all-rules: true
  staticcheck:
    checks:
      - all
      - -SA1019
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
      use-field-name: false
  testifylint:
    enable-all: true
    disable:
      - error-is-as
  usetesting:
    context-background: true
    context-todo: true
    os-chdir: true
    os-mkdir-temp: true
    os-setenv: true
    os-create-temp: true
    os-temp-dir: true

issues:
  exclude-generated: lax
  exclude-dirs:
    - examples
  exclude-rules:
    - linters:
        - noctx
        - perfsprint
      path: _test\.go
    - linters:
        - unused
      path: main\.go$  # Skip unused check for main.go due to CGO/desktop import issues
    - text: "imported and not used"
      path: main\.go$  # Skip typechecking error for desktop import (used in type assertion)

#formatters:
#  enable:
#    - gofumpt
