run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - goimports
    - unused  
    - ineffassign

linters-settings:
  goimports:
    local-prefixes: singbox-launcher

issues:
  exclude-use-default: false
  exclude:
    - "imported and not used"





